version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app-container

  node-app-container:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db-app-container

  db-app-container:
    image: mongo
    volumes:
      - mongo-db:/data/db
    env_file:
      - ./.env

  redis-caching-container:
    image: redis

volumes:
  mongo-db:

  
