version: "3"
services:
  node-app-container:
    build:
      context: .
      args:
        SERVER: development
    volumes:
      - ./server:/app/server
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run dev