version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app-container:
    build:
      context: .
      args:
        SERVER: production
    environment:
      - SERVER=production
    command: npm start