version: '3'
services:
  node-app-container:
    build: .
    image: ruzell/node-app-container
    env_file:
      - ./.env
    depends_on:
      - db-app-container
  db-app-container:
    image: mongo
    volumes:
      - mongo-db:/data/db
    env_file:
      - ./.env

  redis-caching-container:
    image: redis

volumes:
  mongo-db:

  
