version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app-container
  node-app-container:
    build:
      context: .
      args:
        SERVER: production
    env_file:
      - ./.env
    command: npm start